baseURL = "" #相対パスをtrueにしている場合
languageCode = "ja"
title = "餅ツ記"
publishDir = "../docs" # hugoコマンドを実行したときに格納されるディレクトリ
relativeURLs = true #相対パスで保存に変更
theme = "beautifulhugo"

[author]
    name = "きな"
    bio = "Likes pixel art."
    location = "Japan"
    gravatarEmail = "okinakinako@gmail.com"